Rust:
  - "src/**/*.rs"
  - "Cargo.toml"
  - "Cargo.lock"

CI:
  - ".github/workflows/**"

Documentation:
  - "**/*.md"
  - "docs/**"

Configuration:
  - ".gitignore"
  - "*.json"
  - "*.yaml"
  - "*.yml"
  - "*.toml"

License:
  - "LICENSE"

DevContainer:
  - ".devcontainer/**"

Scripts:
  - "scripts/**"

Tests:
  - "tests/**"